version: '3'

networks:
  web:
    external: true

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE:-mwh}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE:-mwh}.${CHATONS_DOMAIN:-localhost}"
